credentials:
  usernames:
    jlynn:
      email: toby2494@gmail.com
      name: Jamie Lynn
      password: b'$2b$12$H.wUFq9IZ002hDDVra7ZD.tq9HP3uia39Z1UE8tMQeDEl523ohchW'
    clynn:
      email: toby2494@gmail.com
      name: Cooper Lynn
      password: def # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - toby2494@gmail.com